name: angular-app-ci
run-name: angular app build by $ {{github.actor}}
on: [push]

jobs:
    run-app:
      runs-on: ubuntu-latest # Can specify Windows or macOS too or your OS.
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4  # Make sure it matches the version of your app
          with:
            node-version: 20.12.0
        
        - run: npm install
        - run: npm run build --prod